#:schema node_modules/wrangler/config-schema.json
name = "migrate-from-c3-template"
compatibility_date = "2024-11-27"
pages_build_output_dir = "./build/client"

[vars]
TITLE = "React Router + Cloudflare Pages"
DESCRIPTION = "A template for building a React Router app with Cloudflare Pages"
